In [7]:
import pandas as pd

In [8]:
import numpy as np

In [9]:
import matplotlib.pyplot as plt

In [10]:
df = pd.DataFrame({
    "maths": [4, 6, 7, 5, 6],
    "cs": [3, 7, 8, 5, 9],
    "result": ["fail", "pass", "pass", "fail", "pass"]
})

In [11]:
df

   maths  cs result
0      4   3   fail
1      6   7   pass
2      7   8   pass
3      5   5   fail
4      6   9   pass

In [13]:
x = df.iloc[:,0:2]
y = df.iloc[:,2]

In [14]:
X

NameError: name 'X' is not defined

In [15]:
x

   maths  cs
0      4   3
1      6   7
2      7   8
3      5   5
4      6   9

In [16]:
y

0    fail
1    pass
2    pass
3    fail
4    pass
Name: result, dtype: object

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
classifier = KNeighborsClassifier(n_neighbors=5)

In [20]:
classifier.fit(x,y)

KNeighborsClassifier()

In [27]:
prediction = classifier.predict([[6,8]])

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [29]:
prediction

array(['pass'], dtype=object)